### ISSUE TITLE
Error on compiling

### ISSUE THREAD

**Issue by Siroopfles** [Beelzebu/Coins3#1]
Hello, when I try to compile the plugin I get this error:
`[ERROR] Failed to execute goal on project coins3-common: Could not resolve dependencies for project com.github.beelzebu:coins3-common:jar:3.0.0-SNAPSHOT: Could not find artifact com.github.beelzebu:coins3-api:jar:3.0-SNAPSHOT in bungeecord-repo (https://oss.sonatype.org/content/repositories/snapshots)`

**Comment by Beelzebu** [comment]
You need to compile the API https://github.com/Beelzebu/Coins3-API
