### ISSUE TITLE
Error in code

### ISSUE THREAD

**Issue by iBuseWinner** [Beelzebu/Coins3#2]
Hey.
Can you fix it?
You trying to use constructor on that line:
https://github.com/Beelzebu/Coins3/blob/master/bukkit/src/com/github/beelzebu/coins/bukkit/CoinsBukkitPlugin.java#L73

But in LoginListener you don't have that constructor:
https://github.com/Beelzebu/Coins3/blob/master/bukkit/src/com/github/beelzebu/coins/bukkit/listener/LoginListener.java

**Comment by Beelzebu** [comment]
Hi, the plugin is using [lombok](https://projectlombok.org/), and LoginListener is annotated with [RequiredArgsConstructor](https://projectlombok.org/features/constructor) https://github.com/Beelzebu/Coins3/blob/master/bukkit/src/com/github/beelzebu/coins/bukkit/listener/LoginListener.java#L35, so it needs CoinsBukkitPlugin in constructor.
Anyways, I removed lombok in my current workspace and will push changes in the next days.
