### ISSUE TITLE
NullPointerException when enable plugin

### ISSUE THREAD

**Issue by iBuseWinner** [Beelzebu/Coins3#3]
Hello again. Compiling your plugin and now getting that error.
Can you help me?

![image](https://user-images.githubusercontent.com/44753872/73655284-b5608480-469e-11ea-8790-b5f08c28fb61.png)

**Comment by iBuseWinner** [comment]
Found error in CommonCoinsPlugin:
getBootstrap() always return null

**Comment by Beelzebu** [comment]
Should be fixed in latest commit.
