### ISSUE TITLE
Is 1.12.2 supported?

### ISSUE THREAD

**Issue by DokanBoy** [Beelzebu/Coins3#5]
Startup error: https://hasteb.in/onamotuz.dump

PaperSpigot 1.12.2

**Comment by Beelzebu** [comment]
Hi, can you please send me the entire server log?

**Comment by DokanBoy** [comment]
https://hasteb.in/ixawuhuf.md

**Comment by Beelzebu** [comment]
The plugin was trying to create a new file in his folder without creating the folder, it should be fixed now.
